# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

# Type of build agent to use to build project - other options include 'macOS-10.15', 'vs2017-win2016', ...
# These are Microsoft-hosted build agents.
pool:
  vmImage: 'ubuntu-latest'

steps:

# Specify the Node.js and NPM version to use for build
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# Build commands
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
